# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lily Riopelle
email: lilykriopelle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings on code.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://lilykriopelle.com" # the base hostname & protocol for your site
twitter_username: lilyriopelle
github_username:  lilykriopelle

# Build settings
markdown: kramdown
